version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: ./server/Services/Auth/Dockerfile
    container_name: auth_service
    ports:
      - "3000:3000"
    env_file:
      - ./server/Services/Auth/.env
    depends_on:
      - db
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: ./server/Services/admin/Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./server/Services/admin/.env
    depends_on:
      - db
    restart: unless-stopped

  bookings:
    build:
      context: .
      dockerfile: ./server/Services/booking/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./server/Services/booking/.env
    depends_on:
      - db
    restart: unless-stopped

  hotel:
    build:
      context: .
      dockerfile: ./server/Services/Hotel/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/Services/Hotel/.env
    depends_on:
      - db
    restart: unless-stopped

  notifications:
    build:
      context: .
      dockerfile: ./server/Services/notifications/Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - ./server/Services/notifications/.env  
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: